spring:
  datasource:

    url: jdbc:postgresql://${POSTGRES_HOST}:6543/${POSTGRES_DB:postgres}?prepareThreshold=0&sslmode=require
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB:postgres}?sslmode=require
    user: ${POSTGRES_FLYWAY_USER:postgres}
    password: ${POSTGRES_FLYWAY_PASSWORD}

    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: false
    validate-on-migrate: true

app:
  swagger:
    enabled: false

logging:
  level:
    com.serveflow: WARN
    org.hibernate: ERROR
    root: ERROR
