spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    out-of-order: false
    validate-on-migrate: true

app:
  swagger:
    enabled: false

logging:
  level:
    com.serveflow: WARN
    org.hibernate: ERROR
    root: ERROR
