ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(500);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS canceled_by  VARCHAR(150);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS canceled_at  TIMESTAMP;
